#!/usr/bin/python3

''' Vidterm: A simple video editor CLI for MoviePY.
'''

import argparse
from moviepy import editor
import sys

parser = argparse.ArgumentParser()

parser.add_argument('-t', '--target', help='Output file.')

# Manage clips
parser.add_argument('-c', '--clip', nargs='+', help='Take a clip from a video file. First argument is the video file. Second argument is optional and is the start time of the clip as taken from the video file (in seconds). Third argument is optional and is the end time in seconds.')

# Video
parser.add_argument('-s', '--speed', type=float, help='Speed up factor. 1.0 is regular speed.')
parser.add_argument('-f', '--fadeout', type=float, help='Fade to black for N seconds.')


class Aggregator(object):

    clips = []
    target = None


    def parse(self, command):
        args = parser.parse_args(command)

        if args.target:
            self.target = args.target

        if args.clip:
            if len(args.clip) == 1:
                self.add_clip(args.clip[0])
            elif len(args.clip) == 3:
                self.add_clip(args.clip[0], args.clip[1], args.clip[2])
            else:
                raise Exception(f'Expected 1 to 3 arguments. Got {len(args.clip)}.')

        if args.speed:
            self.speedx(args.speed)

        if args.fadeout:
            self.fadeout(args.fadeout)

    def add_clip(self, source, start, end):
        print(f'>  Loading {source}')
        print(f'>  >  Clipping from {start} to {end}')
        self.clips.append(editor.VideoFileClip(source).subclip(start, end))

    def speedx(self, factor):
        print(f'>  >  Speeding up by factor: {factor}')
        self.clips[-1] = self.clips[-1].speedx(factor)

    def fadeout(self, duration):
        print(f'>  >  Fading out for {duration} seconds')
        self.clips[-1] = self.clips[-1].fadeout(duration)

    def save(self):
        final = editor.concatenate_videoclips(self.clips)
        final.write_videofile(self.target)


if __name__ == '__main__':
    agg = Aggregator(sys.argv[1])

    idx = []
    for k in range(1, len(sys.argv)):
        if sys.argv[k][0] == '-':
            idx.append(k)

    for i in range(len(idx[:-1])):
        agg.parse(sys.argv[idx[i]: idx[i+1]])
    agg.parse(sys.argv[idx[-1]:])

    agg.save()
